version: "3.7"
services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  temporal:
    image: temporalio/auto-setup:1.21.0
    ports:
      - "7233:7233"
    environment:
      - DB=mongodb
      - MONGO_SEEDS=mongo
      - MONGO_USER=temporal
      - MONGO_PASSWORD=temporal
      - MONGO_DATABASE=temporal
    depends_on:
      - mongo